kind: Service
apiVersion: v1
metadata:
  name: lm-demo-grpc
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: lm-demo
  ports:
    - name: http
      port: 7070
      targetPort: 7070
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lm-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: lm-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lm-demo
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: server
          image: lm-demo:latest
          imagePullPolicy: Always

          resources:
            requests:
              cpu: 20m
              memory: 1Gi
            limits:
              cpu: 8
              memory: 10Gi
          volumeMounts:
            - name: lm-demo-datadir
              mountPath: "/opt/model_store"
      volumes:
        - name: lm-demo-datadir
          persistentVolumeClaim:
            claimName: lm-demo-datadir
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lm-demo-datadir
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
